version: '3.3'
services:
  web:
    volumes:
      - type: volume
        source: frozen
        target: /www/frozen
        volume:
          read_only: true
    depends_on:
      - chill
  chill:
    build:
      context: ./
      dockerfile: freeze.Dockerfile
    volumes:
      - type: volume
        source: frozen
        target: /usr/run/frozen
    command: freeze
volumes:
  frozen:
