version: '3.3'
services:
  web:
    build:
      args:
        - conf=./web-nginx.development.conf
    ports:
      - "8080:80"
    depends_on:
      - chill
  chill:
    command: run
    volumes:
      - ./:/usr/run/
        # TODO:
        #- type: bind
        #- source:
  api:
    volumes:
      - type: bind
        source: ./site.cfg
        target: /code/site.cfg
        read_only: true
      - type: bind
        source: ./package.json
        target: /code/package.json
        read_only: true
      - type: bind
        source: ./api/src
        target: /code/src
